// Geographic data for filtering works by author affiliation.
// Continents follow OpenAlex's UN M49-based mapping; country codes are
// ISO 3166-1 alpha-2, which is what OpenAlex's `institutions.country_code`
// filter expects. The grouping mirrors OpenAlex's continent assignment so
// that the UI can scope the country combobox to the selected regions.

export interface Continent {
  value: string;
  label: string;
}

export const CONTINENTS: readonly Continent[] = [
  { value: "africa", label: "Africa" },
  { value: "asia", label: "Asia" },
  { value: "europe", label: "Europe" },
  { value: "north_america", label: "North America" },
  { value: "oceania", label: "Oceania" },
  { value: "south_america", label: "South America" },
] as const;

export const VALID_CONTINENTS = new Set(CONTINENTS.map((c) => c.value));

export interface Country {
  code: string;
  name: string;
  continent: string;
}

// ISO 3166-1 alpha-2 codes grouped by OpenAlex continent.
// Antarctica is omitted: negligible research output and no institutions
// of consequence in the OpenAlex dataset.
export const COUNTRIES: readonly Country[] = [
  // Africa
  { code: "dz", name: "Algeria", continent: "africa" },
  { code: "ao", name: "Angola", continent: "africa" },
  { code: "bj", name: "Benin", continent: "africa" },
  { code: "bw", name: "Botswana", continent: "africa" },
  { code: "bf", name: "Burkina Faso", continent: "africa" },
  { code: "bi", name: "Burundi", continent: "africa" },
  { code: "cm", name: "Cameroon", continent: "africa" },
  { code: "cv", name: "Cape Verde", continent: "africa" },
  { code: "cf", name: "Central African Republic", continent: "africa" },
  { code: "td", name: "Chad", continent: "africa" },
  { code: "km", name: "Comoros", continent: "africa" },
  { code: "cg", name: "Congo", continent: "africa" },
  { code: "cd", name: "Democratic Republic of the Congo", continent: "africa" },
  { code: "ci", name: "Côte d'Ivoire", continent: "africa" },
  { code: "dj", name: "Djibouti", continent: "africa" },
  { code: "eg", name: "Egypt", continent: "africa" },
  { code: "gq", name: "Equatorial Guinea", continent: "africa" },
  { code: "er", name: "Eritrea", continent: "africa" },
  { code: "sz", name: "Eswatini", continent: "africa" },
  { code: "et", name: "Ethiopia", continent: "africa" },
  { code: "ga", name: "Gabon", continent: "africa" },
  { code: "gm", name: "Gambia", continent: "africa" },
  { code: "gh", name: "Ghana", continent: "africa" },
  { code: "gn", name: "Guinea", continent: "africa" },
  { code: "gw", name: "Guinea-Bissau", continent: "africa" },
  { code: "ke", name: "Kenya", continent: "africa" },
  { code: "ls", name: "Lesotho", continent: "africa" },
  { code: "lr", name: "Liberia", continent: "africa" },
  { code: "ly", name: "Libya", continent: "africa" },
  { code: "mg", name: "Madagascar", continent: "africa" },
  { code: "mw", name: "Malawi", continent: "africa" },
  { code: "ml", name: "Mali", continent: "africa" },
  { code: "mr", name: "Mauritania", continent: "africa" },
  { code: "mu", name: "Mauritius", continent: "africa" },
  { code: "ma", name: "Morocco", continent: "africa" },
  { code: "mz", name: "Mozambique", continent: "africa" },
  { code: "na", name: "Namibia", continent: "africa" },
  { code: "ne", name: "Niger", continent: "africa" },
  { code: "ng", name: "Nigeria", continent: "africa" },
  { code: "rw", name: "Rwanda", continent: "africa" },
  { code: "st", name: "São Tomé and Príncipe", continent: "africa" },
  { code: "sn", name: "Senegal", continent: "africa" },
  { code: "sc", name: "Seychelles", continent: "africa" },
  { code: "sl", name: "Sierra Leone", continent: "africa" },
  { code: "so", name: "Somalia", continent: "africa" },
  { code: "za", name: "South Africa", continent: "africa" },
  { code: "ss", name: "South Sudan", continent: "africa" },
  { code: "sd", name: "Sudan", continent: "africa" },
  { code: "tz", name: "Tanzania", continent: "africa" },
  { code: "tg", name: "Togo", continent: "africa" },
  { code: "tn", name: "Tunisia", continent: "africa" },
  { code: "ug", name: "Uganda", continent: "africa" },
  { code: "eh", name: "Western Sahara", continent: "africa" },
  { code: "zm", name: "Zambia", continent: "africa" },
  { code: "zw", name: "Zimbabwe", continent: "africa" },

  // Asia
  { code: "af", name: "Afghanistan", continent: "asia" },
  { code: "am", name: "Armenia", continent: "asia" },
  { code: "az", name: "Azerbaijan", continent: "asia" },
  { code: "bh", name: "Bahrain", continent: "asia" },
  { code: "bd", name: "Bangladesh", continent: "asia" },
  { code: "bt", name: "Bhutan", continent: "asia" },
  { code: "bn", name: "Brunei", continent: "asia" },
  { code: "kh", name: "Cambodia", continent: "asia" },
  { code: "cn", name: "China", continent: "asia" },
  { code: "cy", name: "Cyprus", continent: "asia" },
  { code: "ge", name: "Georgia", continent: "asia" },
  { code: "in", name: "India", continent: "asia" },
  { code: "id", name: "Indonesia", continent: "asia" },
  { code: "ir", name: "Iran", continent: "asia" },
  { code: "iq", name: "Iraq", continent: "asia" },
  { code: "il", name: "Israel", continent: "asia" },
  { code: "jp", name: "Japan", continent: "asia" },
  { code: "jo", name: "Jordan", continent: "asia" },
  { code: "kz", name: "Kazakhstan", continent: "asia" },
  { code: "kw", name: "Kuwait", continent: "asia" },
  { code: "kg", name: "Kyrgyzstan", continent: "asia" },
  { code: "la", name: "Laos", continent: "asia" },
  { code: "lb", name: "Lebanon", continent: "asia" },
  { code: "my", name: "Malaysia", continent: "asia" },
  { code: "mv", name: "Maldives", continent: "asia" },
  { code: "mn", name: "Mongolia", continent: "asia" },
  { code: "mm", name: "Myanmar", continent: "asia" },
  { code: "np", name: "Nepal", continent: "asia" },
  { code: "kp", name: "North Korea", continent: "asia" },
  { code: "om", name: "Oman", continent: "asia" },
  { code: "pk", name: "Pakistan", continent: "asia" },
  { code: "ps", name: "Palestine", continent: "asia" },
  { code: "ph", name: "Philippines", continent: "asia" },
  { code: "qa", name: "Qatar", continent: "asia" },
  { code: "sa", name: "Saudi Arabia", continent: "asia" },
  { code: "sg", name: "Singapore", continent: "asia" },
  { code: "kr", name: "South Korea", continent: "asia" },
  { code: "lk", name: "Sri Lanka", continent: "asia" },
  { code: "sy", name: "Syria", continent: "asia" },
  { code: "tw", name: "Taiwan", continent: "asia" },
  { code: "tj", name: "Tajikistan", continent: "asia" },
  { code: "th", name: "Thailand", continent: "asia" },
  { code: "tl", name: "Timor-Leste", continent: "asia" },
  { code: "tr", name: "Turkey", continent: "asia" },
  { code: "tm", name: "Turkmenistan", continent: "asia" },
  { code: "ae", name: "United Arab Emirates", continent: "asia" },
  { code: "uz", name: "Uzbekistan", continent: "asia" },
  { code: "vn", name: "Vietnam", continent: "asia" },
  { code: "ye", name: "Yemen", continent: "asia" },

  // Europe
  { code: "al", name: "Albania", continent: "europe" },
  { code: "ad", name: "Andorra", continent: "europe" },
  { code: "at", name: "Austria", continent: "europe" },
  { code: "by", name: "Belarus", continent: "europe" },
  { code: "be", name: "Belgium", continent: "europe" },
  { code: "ba", name: "Bosnia and Herzegovina", continent: "europe" },
  { code: "bg", name: "Bulgaria", continent: "europe" },
  { code: "hr", name: "Croatia", continent: "europe" },
  { code: "cz", name: "Czechia", continent: "europe" },
  { code: "dk", name: "Denmark", continent: "europe" },
  { code: "ee", name: "Estonia", continent: "europe" },
  { code: "fi", name: "Finland", continent: "europe" },
  { code: "fr", name: "France", continent: "europe" },
  { code: "de", name: "Germany", continent: "europe" },
  { code: "gr", name: "Greece", continent: "europe" },
  { code: "hu", name: "Hungary", continent: "europe" },
  { code: "is", name: "Iceland", continent: "europe" },
  { code: "ie", name: "Ireland", continent: "europe" },
  { code: "it", name: "Italy", continent: "europe" },
  { code: "xk", name: "Kosovo", continent: "europe" },
  { code: "lv", name: "Latvia", continent: "europe" },
  { code: "li", name: "Liechtenstein", continent: "europe" },
  { code: "lt", name: "Lithuania", continent: "europe" },
  { code: "lu", name: "Luxembourg", continent: "europe" },
  { code: "mt", name: "Malta", continent: "europe" },
  { code: "md", name: "Moldova", continent: "europe" },
  { code: "mc", name: "Monaco", continent: "europe" },
  { code: "me", name: "Montenegro", continent: "europe" },
  { code: "nl", name: "Netherlands", continent: "europe" },
  { code: "mk", name: "North Macedonia", continent: "europe" },
  { code: "no", name: "Norway", continent: "europe" },
  { code: "pl", name: "Poland", continent: "europe" },
  { code: "pt", name: "Portugal", continent: "europe" },
  { code: "ro", name: "Romania", continent: "europe" },
  { code: "ru", name: "Russia", continent: "europe" },
  { code: "sm", name: "San Marino", continent: "europe" },
  { code: "rs", name: "Serbia", continent: "europe" },
  { code: "sk", name: "Slovakia", continent: "europe" },
  { code: "si", name: "Slovenia", continent: "europe" },
  { code: "es", name: "Spain", continent: "europe" },
  { code: "se", name: "Sweden", continent: "europe" },
  { code: "ch", name: "Switzerland", continent: "europe" },
  { code: "ua", name: "Ukraine", continent: "europe" },
  { code: "gb", name: "United Kingdom", continent: "europe" },
  { code: "va", name: "Vatican City", continent: "europe" },

  // North America
  { code: "ai", name: "Anguilla", continent: "north_america" },
  { code: "ag", name: "Antigua and Barbuda", continent: "north_america" },
  { code: "bs", name: "Bahamas", continent: "north_america" },
  { code: "bb", name: "Barbados", continent: "north_america" },
  { code: "bz", name: "Belize", continent: "north_america" },
  { code: "bm", name: "Bermuda", continent: "north_america" },
  { code: "vg", name: "British Virgin Islands", continent: "north_america" },
  { code: "ca", name: "Canada", continent: "north_america" },
  { code: "ky", name: "Cayman Islands", continent: "north_america" },
  { code: "cr", name: "Costa Rica", continent: "north_america" },
  { code: "cu", name: "Cuba", continent: "north_america" },
  { code: "dm", name: "Dominica", continent: "north_america" },
  { code: "do", name: "Dominican Republic", continent: "north_america" },
  { code: "sv", name: "El Salvador", continent: "north_america" },
  { code: "gl", name: "Greenland", continent: "north_america" },
  { code: "gd", name: "Grenada", continent: "north_america" },
  { code: "gt", name: "Guatemala", continent: "north_america" },
  { code: "ht", name: "Haiti", continent: "north_america" },
  { code: "hn", name: "Honduras", continent: "north_america" },
  { code: "jm", name: "Jamaica", continent: "north_america" },
  { code: "mx", name: "Mexico", continent: "north_america" },
  { code: "ms", name: "Montserrat", continent: "north_america" },
  { code: "ni", name: "Nicaragua", continent: "north_america" },
  { code: "pa", name: "Panama", continent: "north_america" },
  { code: "pr", name: "Puerto Rico", continent: "north_america" },
  { code: "kn", name: "Saint Kitts and Nevis", continent: "north_america" },
  { code: "lc", name: "Saint Lucia", continent: "north_america" },
  { code: "pm", name: "Saint Pierre and Miquelon", continent: "north_america" },
  {
    code: "vc",
    name: "Saint Vincent and the Grenadines",
    continent: "north_america",
  },
  { code: "tt", name: "Trinidad and Tobago", continent: "north_america" },
  { code: "tc", name: "Turks and Caicos Islands", continent: "north_america" },
  { code: "us", name: "United States", continent: "north_america" },
  { code: "vi", name: "U.S. Virgin Islands", continent: "north_america" },

  // Oceania
  { code: "as", name: "American Samoa", continent: "oceania" },
  { code: "au", name: "Australia", continent: "oceania" },
  { code: "ck", name: "Cook Islands", continent: "oceania" },
  { code: "fj", name: "Fiji", continent: "oceania" },
  { code: "gu", name: "Guam", continent: "oceania" },
  { code: "ki", name: "Kiribati", continent: "oceania" },
  { code: "mh", name: "Marshall Islands", continent: "oceania" },
  { code: "fm", name: "Micronesia", continent: "oceania" },
  { code: "nr", name: "Nauru", continent: "oceania" },
  { code: "nc", name: "New Caledonia", continent: "oceania" },
  { code: "nz", name: "New Zealand", continent: "oceania" },
  { code: "nu", name: "Niue", continent: "oceania" },
  { code: "mp", name: "Northern Mariana Islands", continent: "oceania" },
  { code: "pw", name: "Palau", continent: "oceania" },
  { code: "pg", name: "Papua New Guinea", continent: "oceania" },
  { code: "ws", name: "Samoa", continent: "oceania" },
  { code: "sb", name: "Solomon Islands", continent: "oceania" },
  { code: "to", name: "Tonga", continent: "oceania" },
  { code: "tv", name: "Tuvalu", continent: "oceania" },
  { code: "vu", name: "Vanuatu", continent: "oceania" },

  // South America
  { code: "ar", name: "Argentina", continent: "south_america" },
  { code: "bo", name: "Bolivia", continent: "south_america" },
  { code: "br", name: "Brazil", continent: "south_america" },
  { code: "cl", name: "Chile", continent: "south_america" },
  { code: "co", name: "Colombia", continent: "south_america" },
  { code: "ec", name: "Ecuador", continent: "south_america" },
  { code: "fk", name: "Falkland Islands", continent: "south_america" },
  { code: "gf", name: "French Guiana", continent: "south_america" },
  { code: "gy", name: "Guyana", continent: "south_america" },
  { code: "py", name: "Paraguay", continent: "south_america" },
  { code: "pe", name: "Peru", continent: "south_america" },
  { code: "sr", name: "Suriname", continent: "south_america" },
  { code: "uy", name: "Uruguay", continent: "south_america" },
  { code: "ve", name: "Venezuela", continent: "south_america" },
] as const;

export const COUNTRY_BY_CODE = new Map<string, Country>(
  COUNTRIES.map((c) => [c.code, c]),
);

export const VALID_COUNTRY_CODES = new Set(COUNTRIES.map((c) => c.code));

export function countryName(code: string): string {
  return COUNTRY_BY_CODE.get(code)?.name ?? code.toUpperCase();
}
